---
name: unittests

on:
  push:
    branches: ["feat/unittest-action"]
  pull_requests:
    branches: ["master"]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: run tests
        run: |
          go test -cover ./use_cases/**
