---
name: Unit Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: run tests
        run: |
          go test -v ./use_cases/**
          go test -cover ./use_cases/**
